# Generated by Django 2.0.9 on 2018-10-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181028_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='achievements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='running_club',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
