# Generated by Django 2.0.9 on 2018-10-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('shoe_type', models.CharField(choices=[('flats', 'FLATS'), ('spikes', 'SPIKES')], max_length=50)),
                ('weight', models.IntegerField()),
            ],
        ),
    ]
