# Generated by Django 2.0.9 on 2018-10-29 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('customer_overall_rating', models.IntegerField(blank=True, null=True)),
                ('customer_fit_rating', models.IntegerField(blank=True, null=True)),
                ('customer_support_rating', models.IntegerField(blank=True, null=True)),
                ('customer_race_experience', models.TextField(blank=True, null=True)),
                ('customer_review', models.TextField(blank=True, null=True)),
            ],
        ),
        # migrations.AddField(
        #     model_name='customerreview',
        #     name='shoe_model',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Shoe'),
        # ),
        migrations.AddField(
            model_name='customerreview',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
