# Generated by Django 2.0.9 on 2018-10-25 12:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=50)),
                ('strapline', models.TextField()),
                ('description', models.TextField()),
                ('shoe_type', models.CharField(choices=[('flats', 'FLATS'), ('track spikes', 'TRACK_SPIKES'), ('cross country spikes', 'CROSS_COUNTRY_SPIKES'), ('pluggers', 'PLUGGERS')], max_length=50)),
                ('weight', models.IntegerField()),
                ('drop_height', models.IntegerField()),
                ('price', models.IntegerField()),
                ('primary_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=10, null=True, validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(1)])),
                ('stock', models.IntegerField(default=10, null=True)),
                ('shoe_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Shoe')),
            ],
        ),
    ]
