# Generated by Django 2.0.9 on 2018-10-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='drop_height',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
