# Generated by Django 2.0.9 on 2018-10-29 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=50)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'MALE'), ('Female', 'FEMALE')], max_length=50, null=True)),
                ('strapline', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('shoe_type', models.CharField(choices=[('flats', 'FLATS'), ('track spikes', 'TRACK_SPIKES'), ('cross country spikes', 'CROSS_COUNTRY_SPIKES'), ('pluggers', 'PLUGGERS')], max_length=50)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('weight_ranking', models.IntegerField(blank=True, null=True)),
                ('wet_weight', models.IntegerField(blank=True, null=True)),
                ('wet_weight_ranking', models.IntegerField(blank=True, null=True)),
                ('flexibility_ranking', models.IntegerField(blank=True, null=True)),
                ('fit_ranking', models.CharField(blank=True, max_length=50, null=True)),
                ('support_ranking', models.IntegerField(blank=True, null=True)),
                ('spikes_included', models.CharField(blank=True, max_length=100, null=True)),
                ('midsole_drop_height', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('primary_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('blog_link', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Shoe')),
            ],
        ),
        migrations.AddField(
            model_name='productimage',
            name='shoe_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Shoe'),
        ),
        migrations.AddField(
            model_name='customerreview',
            name='shoe_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Shoe'),
        ),
    ]
