# Generated by Django 2.0.9 on 2018-10-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklevel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
