# Generated by Django 2.0.9 on 2018-10-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shoe_drop_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='shoe_type',
            field=models.CharField(choices=[('flats', 'FLATS'), ('spikes', 'SPIKES'), ('pluggers', 'PLUGGERS')], max_length=50),
        ),
    ]
