# Generated by Django 2.0.9 on 2018-10-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_create_other_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
