# Generated by Django 2.0.9 on 2018-10-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_change_stock_to_decimal_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='size',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
