# Generated by Django 2.0.9 on 2018-10-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20181008_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='shoe_type',
            field=models.CharField(choices=[('flats', 'FLATS'), ('track spikes', 'TRACK SPIKES'), ('cross country spikes', 'CROSS COUNTRY SPIKES'), ('pluggers', 'PLUGGERS')], max_length=50),
        ),
    ]
