# Generated by Django 2.0.9 on 2018-10-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20181025_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocklevel',
            name='id',
        ),
        migrations.AlterField(
            model_name='stocklevel',
            name='stock',
            field=models.IntegerField(default=10, primary_key=True, serialize=False),
        ),
    ]
