# Generated by Django 2.0.9 on 2018-10-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20181008_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='shoe_type',
            field=models.CharField(choices=[('flats', 'FLATS'), ('track spikes', 'TRACK_SPIKES'), ('cross country spikes', 'CROSS_COUNTRY_SPIKES'), ('pluggers', 'PLUGGERS')], max_length=50),
        ),
    ]
