# Generated by Django 2.0.9 on 2018-10-27 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0004_auto_20181025_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('customer_overall_rating', models.IntegerField(blank=True, null=True)),
                ('customer_fit_rating', models.IntegerField(blank=True, null=True)),
                ('customer_support_rating', models.IntegerField(blank=True, null=True)),
                ('cusstomer_race_experience', models.TextField(blank=True, null=True)),
                ('customer_review', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='drop_height',
        ),
        migrations.AddField(
            model_name='shoe',
            name='blog_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shoe',
            name='fit_ranking',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shoe',
            name='flexibility_ranking',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoe',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'MALE'), ('Female', 'FEMALE')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shoe',
            name='midsole_drop_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoe',
            name='spikes_included',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shoe',
            name='support_ranking',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoe',
            name='weight_ranking',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoe',
            name='wet_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoe',
            name='wet_weight_ranking',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='primary_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='strapline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stocklevel',
            name='shoe_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Shoe'),
        ),
        migrations.AddField(
            model_name='productimages',
            name='shoe_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Shoe'),
        ),
        migrations.AddField(
            model_name='customerreview',
            name='shoe_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Shoe'),
        ),
        migrations.AddField(
            model_name='customerreview',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
