# Generated by Django 2.0.9 on 2018-10-10 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20181008_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='price',
            field=models.IntegerField(default=70),
            preserve_default=False,
        ),
    ]
