# Generated by Django 2.0.9 on 2018-10-27 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20181027_0714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerreview',
            old_name='cusstomer_race_experience',
            new_name='customer_race_experience',
        ),
    ]
