# Generated by Django 2.0.9 on 2018-10-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_shoe_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='primary_image',
            field=models.ImageField(default='/Users/harryphelps/Development/Projects/full-stack-frameworks-project/media/img/IMG_2704.JPG', upload_to=''),
            preserve_default=False,
        ),
    ]
