# Generated by Django 2.0.9 on 2018-10-14 10:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_shoe_primary_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(1)])),
                ('stock', models.IntegerField(default=10)),
                ('shoe_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Shoe')),
            ],
        ),
    ]
