# Generated by Django 2.0.9 on 2018-10-14 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20181014_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocklevel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='stocklevel',
            name='shoe_model',
        ),
        migrations.AddField(
            model_name='stocklevel',
            name='shoe_ptr',
            field=models.OneToOneField(auto_created=True, default=10, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Shoe'),
            preserve_default=False,
        ),
    ]
