# Generated by Django 2.0.9 on 2018-10-14 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20181014_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocklevel',
            name='shoe_ptr',
        ),
        migrations.AddField(
            model_name='stocklevel',
            name='shoe_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.Shoe'),
            preserve_default=False,
        ),
    ]
