# Generated by Django 2.0.9 on 2018-10-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20181014_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='strapline',
            field=models.TextField(default='A really great shoe'),
            preserve_default=False,
        ),
    ]
