# Generated by Django 2.0.9 on 2018-10-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_shoe_strapline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklevel',
            name='id',
            field=models.BigIntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
