# Generated by Django 2.0.9 on 2018-10-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20181024_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklevel',
            name='id',
            field=models.AutoField(auto_created=True, default=10, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
